


<html>
    <head> 
        
    <!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script>    

  function init_map() {
    var var_location = new google.maps.LatLng(45.430817,12.331516);

    var var_mapoptions = {
      center: var_location,
      zoom: 14
    };

    var var_marker = new google.maps.Marker({
        position: var_location,
        map: var_map,
        title:"Venice"});

    var var_map = new google.maps.Map(document.getElementById("map-container"),
        var_mapoptions);

    var_marker.setMap(var_map); 

  }


  google.maps.event.addDomListener(window, 'load', init_map);

</script>    
        
        
    </head>
    <body>

<table class="table">

<?php
 if($this->city !== null)
  {
  	//var_dump($this->user["id"] );exit;
  	?>
<tr style="background-color:blue">
	<td><?php echo $this->city["id"];  ?></td>

</tr>
<tr>
<td><?php echo $this->city["name"]; ?></td>
	

</tr>

<tr>
<td><?php echo $this->city["description"];?></td>
	
</tr>





<tr>
<td><img src"<?php echo $this->city["image"];?>" height='42' width='42'</td>
	
</tr>

<?php
  }
?>
</table>
    </body>
    </html>