


<?php
 if($this->city !== null)
  {
  	//var_dump($this->user["id"] );exit;
  	?>

<div class="item">
	<img src="<?=  $this->city["image"];?>"  style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h3><?=  $this->city["name"]; ?></h3>
          <p><?= $this->city["description"];?></p>
        </div>
</div>	


<?php
  }
?>
 


<div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8qj-3E6nRcvPyJP9DwpAZ3Xr_iSq_ot8&callback=initMap"
    async defer></script>

      
      <h2>available location  <?php echo "( ".$this->countItems." )"; ?></h2> 
<p> <?php foreach ($this->locations as $tree): ?>
 <?php echo "reservation_id :: " .$tree['id'] ?>
    <br/> <?php echo "user_id :: ".$tree['name'] ?><br/>
      <?php echo "reservation_id :: " .$tree['image'] ?><br/>
 <?php endforeach; ?> </p> <br/> 
<a href="<?php echo $this->url(array('controller'=>'city','action'=>'details','p'=>$this->previousPage)) ?>">
    previous </a> 
        <?php echo "".$this->currentPage."/".$this->countPages; ?> 
<a href="<?php echo $this->url(array('controller'=>'city','action'=>'details','p'=>$this->nextPage)) ?>"> next </a> <br/>
      
      
   