<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>
    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
        
        Pick your Date: <?php echo $this->datePicker("dp1", '', array('defaultDate' => date('Y-m-d h:m:s', time()))); ?>
    </div>
</div>
<form id="fr">
    <input type="text" id="username" name="q">
    <input type="button" id="name" value="echo name">
</form>
<div id="te">
    
</div>
<script>
$("#username").autocomplete({
    source: function( request, response ) {
    var name = $("#username").val();
        $.ajax({
        url: "/index/ajax",
        data: { name: name },
        dataType: "json",
        success: function( data ) {
            $("#username").autocomplete({
                                           source : data,
                                           
                                       }
                                       );
        }
    })},
    minLength : 0 
    });
    
    $('#name').on('click',function () {
        var text = $("#username").val();
    $.ajax(
        {
            url:'/index/add',
            method:'POST',
            data:{
                'name' : text,
            },
            success:echo_my_name
        }
    );
    function echo_my_name (data)
    {
        //alert(data);
        var parser = JSON.parse(data);
        $('te').children().append(parser);
        
      	// after parsing
        alert(parser);
        
        }
    });
</script>