<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="/css/bootstrap.min.css">
    <body>
        <div class="container">
            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Reserve Room</button>
            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content " >
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h1>Search for hotel</h1>
                        </div>
                        <div class="modal-body" id="imp" >
                            <div>

                                <input type="text" id="hotel">
                                
                                
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input  class="form-control" type="button" id="find" value="search">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <input type="text" id ="df">
        <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script> 
        <script src="//cdn.jsdelivr.net/webshim/1.14.5/polyfiller.js"></script>
        <script>
            webshims.setOptions('forms-ext', {types: 'date'});
            webshims.polyfill('forms forms-ext');
            $.webshims.formcfg = {
                en: {
                    dFormat: '-',
                    dateSigns: '-',
                    patterns: {
                        d: "yy-mm-dd"
                    }
                }
            };
        </script>
        <script src="/js/jquery-ui-1.11.4/jquery-ui.js"></script>
           <link rel="stylesheet" href="/js/jquery-ui-1.11.4/jquery-ui.css">
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/bootstrap-datepicker.js"></script> 
        <script src="/js/reserve.js"></script>
</html>
