<html>
    <head> 
    </head>
    <body>
        <table class="table">
            <?php
            $auth = Zend_Auth::getInstance();
            $storage = $auth->getStorage();
            $sessionRead = $storage->read();
            if (isset($sessionRead)) {
                $user_id = $sessionRead->id;  // must be get from sesion
                $logedusername =$sessionRead->name;
                $logedimage = $sessionRead->image;
            }
            if ($this->city !== null) {
                ?>
                <tr style="background-color:blue">
                    <td><?php echo $this->city["id"]; ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->city["name"]; ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->city["description"]; ?></td>
                </tr>
                <tr>
                    <td><img src="<?php echo $this->city["image"]; ?>" height='42' width='42'</td>
                </tr>
    <?php
}
?>
        </table>
        <div class='container-fluid'>
            <div class='container' id="posts">
<?php
foreach ($this->posts as $key => $post):
    $user = new Application_Model_User();
        
    $us = $user->showUser($post['user_id'])[0];
    $username = $us['name'];
    $image = $us['image'];
    ?>
                    <div id="post-details<?= $post['id'] ?>">
                        <label><?= $username ?></label>
                        <img src="<?= $image ?>" width="50" height="50">
                        <textarea id ="post<?= $post['id'] ?>" rows="20" cols="100" disabled="disabled" ><?= $post['content'] ?></textarea>
                               <?php if(isset($sessionRead)){if($us['id'] == $user_id){?>
                        <input type = "button" id="postedit<?= $post['id'] ?>" value="edit" onclick="edit(<?= $post['id'] ?>)"/>
                        <input type = "button" id="postdel<?= $post['id'] ?>" value="delete" onclick="del(<?= $post['id'] ?>)"/>
                               <?php }}?>
                        <?php if(isset($sessionRead)) { ?>
                    
                        <div>
                            <label>Add New Comment : </label>
                            <textarea id ="addcom<?= $post['id'] ?>" rows="3" cols="100"></textarea>
                            <input type="button" value="Add" onclick="addcom(<?= $post['id'] ?>,<?= $user_id ?>, '<?= $logedusername ?>', '<?= $logedimage ?>')">
                        </div> 
                            <?php  } ?>
    <?php
    //for ($i = 0; $i < count($this->comments); $i++) {
    foreach ($this->comments[$post['id']] as $key => $comment):
        $us = $user->showUser($comment['user_id'])[0];
        $username = $us['name'];
        $image = $us['image'];
        ?>
                            <div id="comment-details" style="margin-left: 50px;">
                                <hr>
                                <label><?= $username ?></label>
                                <img src="<?= $image ?>" width="50" height="50">
                                <textarea id ="com<?= $comment['id'] ?>" rows="3" cols="100" disabled="disabled"><?= $comment['content'] ?></textarea>
                                
                               <?php if(isset($sessionRead)){if($us['id'] == $user_id){?>
                                    <input type = "button" id="comedit<?= $comment['id'] ?>" value="edit" onclick="editcom(<?= $comment['id'] ?>)"/>
                                    <input type = "button" id="comdel<?= $comment['id'] ?>" value="delete" onclick="delcom(<?= $comment['id'] ?>)"/>
                               <?php }}?>

                            </div>
        <?php
    endforeach;
    //} 
    ?>

                    
                        <hr>
                    </div>
                   
<?php endforeach; ?>

            </div>

            <?php if(isset($sessionRead)) { ?>
                    
            <div>
                <label>Add New Post : </label>
                <textarea id ="addpost" rows="20" cols="100"></textarea>
                <input type="button" value="Add" onclick="add(<?= $this->city["id"] ?>,<?= $user_id ?>, '<?= $logedusername ?>', '<?= $logedimage ?>')">
            </div> 
             <?php  } ?>
            <script src="/js/jquery-1.11.1.min.js"></script>           
            <script src="/js/comments.js"></script>