<link href="/css/styleee.css" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Alley Signup & Signin Form Tab Form,Login Forms,Sign up Forms,Registration Forms,News letter Forms,Elements"./>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<script src="/js/jquery.min.js"></script>
<script src="/js/easyResponsiveTabs.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#horizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion           
            width: 'auto', //auto or any width like 600px
            fit: true   // 100% fit in a container
        });
    });
</script>
<div class="main-content">
    <div class="sap_tabs">	

        <div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
            <ul>
                <li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span>HOTEL RESERVATION </span></li>
            </ul>
            <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
                <div class="form-group-lg">
                    <div class="register">
                        <form>	
                            <?php echo $this->form; ?>
                        </form>
                    </div>
                </div>
               
            </div>
             
            		        					            	      
        </div>
    </div>
</div>
        
    <table id="rmdata" class="table-bordered table-striped">
        <thead>
            <th>Room Id</th>
            <th>Number Of Persons</th>
            <td>Price</td>
            <th>Action</th>
        </thead>
    </table>
<link rel="stylesheet" href="/css/datepicker.css"> 
            <script src="/js/bootstrap-datepicker.js"></script>
            <script src="/js/jquery-ui-1.11.4/jquery-ui.js"></script>
            <link rel="stylesheet" href="/js/jquery-ui-1.11.4/jquery-ui.css">
            <script src="/js/bootstrap.min.js"></script>
            <script src="/js/bootstrap-datepicker.js"></script> 
            <script src="/js/reservehotel.js"> </script>	

            
<div id="hello" class="banner-bottom">
	<div class="container">
		<div class="btm-header">
			<h3 class="tittle"> LETS START ツ </h3>
		
		</div>
	</div>
</div>
            
         