
<!--$room_id,
                        $user_id,
                        $start,
                        $end,
                        $sumbit,
                        $reset-->


<link href="/css/styleee.css" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Alley Signup & Signin Form Tab Form,Login Forms,Sign up Forms,Registration Forms,News letter Forms,Elements"./>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
</script>
<script src="/js/jquery.min.js"></script>
<script src="/js/easyResponsiveTabs.js" type="text/javascript"></script>


<script type="text/javascript">
    $(document).ready(function () {
        $('#horizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion           
            width: 'auto', //auto or any width like 600px
            fit: true   // 100% fit in a container
        });
    });
</script>

<br> <br> <br>
<div> </div>
<div class="main-content">
    <div class="sap_tabs">	

        <div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">

            <ul>
                <li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span>HOTEL RESERVATION </span></li>
               

            </ul>		
            <!---->
            <!--$room_id,
                        $user_id,
                        $start,
                        $end,
                        $sumbit,
                        $reset-->


            <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
                <div class="facts">
                    <!--login1-->
                    <div class="register">
                        <form>	
                           <?php echo $this->form; ?>
                        </form>
                    </div>
                </div>
            </div>	

             <link rel="stylesheet" href="/css/datepicker.css"> 
 <script src="/js/bootstrap-datepicker.js"></script>
 
 <script> 
     $('#start').datepicker('show');
     
    $('#end').datepicker('show'); 
//     $( '#date_from').html( "<span class='glyphicon glyphicon-calendar form-control-feedback'></span>" ); 
      </script>			        					            	      

        </div>	

    </div>
</div>
