<?php 
echo $this->form;
?>


<script src="https://code.jquery.com/jquery-1.12.0.min.js" ></script>
<script>

$('#show').click(
        function () {

    $.ajax(
        {

            'url':'/user/hanan',
            method:'POST',
            data:{
                'name' : $('#start').val(),
            },
            success:echo_my_name
        }
    );

    function echo_my_name (data)
    {
       // alert(data);
      var parser = JSON.parse(data);

      	// after parsing
        alert(parser);
    }
})

</script>