<br /><br />
<div id="view-content">
    <p>View script for controller <b>Clients</b> and script/action name <b>listClients</b></p>
    <table>
        <?php
        foreach ($this->users as $key => $value) {
            if($value['is_enable'] == 0) {
                $action = 'activate';
            } else {
                    $action = 'block';
            
            }
            echo "<tr>" .
            "<td>" . $value['id'] . "</td>" .
            "<td>" . $value['name'] . "</td>" .
            "<td>" . $value['email'] . "</td>" .
            "<td>" . $value['tel'] . "</td>" .
            "<td>" . $value['gender'] . "</td>" .
            "<td> <a href='show-user/uid/" . $value['id'] . "' class='btn btn-primary'> Details </a> </td>" .
            "<td> <a href='$action-user/uid/" . $value['id'] . "' class='btn btn-danger'> $action </a> </td>"
            . "<td> <a href='edit-user/uid/" . $value['id'] . "' class='btn btn-warning'> Update </a> </td>"
            . "</tr>";
        }
        ?>
    </table>

</div>