<br /><br />
<h2>Reservation Car List <?php echo "( ".$this->countItems." )"; ?></h2>
<table class="table table-inverse">
        <tr  class="info">
        <th >Reservation_id</th>
        <th >Car_id</th>
        <th >user_id</th>
        <th >Start_Date</th>
        <th >end_Date</th>
        <th class="text-center">Action</th> 
    </tr>
<?php foreach ($this->trees as $tree): ?>
<tr class="success">
    <td> <?= $tree['id'] ?> </td>
    <td> <?= $tree['car_id'] ?> </td>
    <td> <?= $tree['user_id'] ?> </td>
    <td> <?= $tree['start'] ?> </td>
    <td> <?= $tree['end'] ?> </td>
    <td> <a href="delrescar?id=<?= $tree['id']?>">DELETE</a> <td>
</tr>
<?php endforeach; ?>
</table>
<a href="<?php echo $this->url(array('controller'=>'user','action'=>'listrescar','p'=>$this->previousPage)) ?>"> previous </a>
<?php echo "".$this->currentPage."/".$this->countPages; ?>
<a href="<?php echo $this->url(array('controller'=>'user','action'=>'listrescar','p'=>$this->nextPage)) ?>"> next </a>
<br/>
<br/>
