<br /><br />
<?php
echo $this->form;
?>
<body>
    <script>
       // $('#start').
    function AutoFill()
    {
        alert("hello");
        new Ajax.Request(
        "<?=$this->url(array('controller'=>'user','action'=>'getdata'))?>",
            {
                method:'get',
                parameters: {id: value},
                onSuccess: FillForm,
                onFailed:FillForm
        }
}

function FillForm(rsp)
{
    var card = eval('(' + rsp.responseText + ')');
    $('user_id').value = card.items[0].user_id;
    $('room_id').value = card.items[0].room_id;
} 
</script>
</body>

