<br /><br />
<head>
    

	

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>

</head>
<?php
echo $this->form;
?>


    <script>
        $('#btn').on('click',hello);
        
        function hello () {
           // alert("helllll0");
        jQuery.ajax({
    url: "http://http://localhost/fas7ny/public/user/getdata",
    type: "get",
    //dataType: 'json',
    //data: data,
    success: function(){alert("sucess");},
    error:function(){ alert("fail");}
        })
    }


</script>