<br /><br />

<div class="page-header">
    <h1>DashBoard</h1>
</div>
<div>
    <ul>
        <li id="Users-List" data-toggle="collapse"><a href="admin/listuser">Users List</a></li>
        <li id="Countries-List" data-toggle="collapse"><a href="admin/listcountry">Countries List</a></li>
        <li id="Cities-List" data-toggle="collapse"><a href="admin/listcity">Cities List</a></li>
        <li id="Hotels-List" data-toggle="collapse"><a href="admin/listhotel">Hotels List</a></li>
    </ul>
</div>
    
