<!-- footer -->
<body style="background:rgb(40, 38, 38);">
<div class="footer" style="padding-top: 15px;padding-bottom: 15px;height: 242px;">
    <div class="cbp-spmenu cbp-spmenu-horizontal cbp-spmenu-open">
        <a href="/admin/listuser" class="active" style="font-family: Times New Roman;font-size: 32px;">Users</a>
        <a href="/admin/listcountry" style="font-family: Times New Roman;font-size: 32px;">Countries</a>
        <a href="/admin/listcity" style="font-family: Times New Roman;font-size: 32px;">Cities</a>
        <a href="/admin/listlocation" style="font-family: Times New Roman;font-size: 32px;">Locations</a>
        <a href="/admin/listhotel" style="font-family: Times New Roman;font-size: 32px;">Hotels</a>
    </div>
</div>
</body>

<!--<div class="page-header">
    <h1>DashBoard</h1>
</div>
<div class="dd">
    <ul>
        <li id="Users-List" data-toggle="collapse"><a href="admin/listuser">Users List</a></li>
        <li id="Countries-List" data-toggle="collapse"><a href="admin/listcountry">Countries List</a></li>
        <li id="Cities-List" data-toggle="collapse"><a href="admin/listcity">Cities List</a></li>
        <li id="Locations-List" data-toggle="collapse"><a href="admin/listlocation">Locations List</a></li>
        <li id="Hotels-List" data-toggle="collapse"><a href="admin/listhotel">Hotels List</a></li>
    </ul>
</div>-->
