<br /><br />
<div id="view-content">
	<p>View script for controller <b>Admin</b> and script/action name <b>listuser</b></p>
</div>
<div class="alert alert-info alert-dismissible">
    For Add User.
    <a href='adduser'>ClickHere</a>
    <button type="button" class="close" data-dismiss="alert">
        <span>&times;</span>
    </button>
</div>

<table class="table table-condensed table-striped">
    <?php
    echo "<tr><th> UserName </th><th> UserStatus </th></tr>" ;
    foreach ($this->users as $key => $value) {
        if($value['is_enable'] == 0) {
            $action = 'activateuser';
        } else {
                $action = 'blockuser';

        }
        echo "<tr>" .
        "<td>" . $value['name'] . "</td>" .
        "<td> <a href='$action/uid/" . $value['id'] . "' class='btn btn-danger'> $action </a> </td>".
        "</tr>";
    }
    ?>
</table>