<br /><br />
<div id="view-content">
	<p>View script for controller <b>Admin</b> and script/action name <b>listhotel</b></p>
</div>

<table>
    <?php
    echo "<td> <a class='btn btn-info' href='add'> ADD </a> </td>" ;
    foreach ($this->hotel as $key => $value) {
        echo "<tr>" .
        "<td>" . $value['name'] . "</td>" .
        "<td>" . $value['location'] . "</td>" .
        "<td> <a href='edit-user/uid/" . $value['id'] . "' class='btn btn-warning'> Update </a> </td>".
        "<td> <a href='action-user/uid/" . $value['id'] . "' class='btn btn-danger'> Delete </a> </td>".
        "</tr>";
    }
    ?>
</table>     