<br /><br />
<div id="view-content">
	<p>View script for controller <b>Admin</b> and script/action name <b>listlocation</b></p>
</div>

<div class="alert alert-info alert-dismissible">
    For Add Location.
    <a href='addlocation'>ClickHere</a>
    <button type="button" class="close" data-dismiss="alert">
        <span>&times;</span>
    </button>
</div>

<table class="table table-condensed table-striped">
    <?php
    echo "<tr><th> LocationName </th><th> LocationCityID </th><th> LocationImage </th><th>EditHotel</th><th>DeleteHotel</th></tr>" ;
    foreach ($this->location as $key => $value) {
        echo "<tr>" .
        "<td>" . $value['name'] . "</td>" .
        "<td>" . $value['0'] . "</td>" .
        "<td> <img  src='".$value['image']."' height='42' width='42'>  </td>" .
        "<td> <a href='../admin/editlocation/id/" . $value['id'] . "' class='btn btn-warning'> Edit </a> </td>".
        "<td> <a href='../admin/deletelocation/id/" . $value['id'] . "' class='btn btn-danger'> Delete </a> </td>".
        "</tr>";
    }
    ?>
</table>     
