<br />
<div class="alert alert-info alert-dismissible">
    For Add Hotel.
    <a href='addhotel'>ClickHere</a>
    <button type="button" class="close" data-dismiss="alert">
        <span>&times;</span>
    </button>
</div>

<table class="table table-condensed table-striped">
    <?php
    echo "<tr><th> HotelName </th><th> HotelLocation </th><th> HotelCity </th><th>EditHotel</th><th>DeleteHotel</th></tr>" ;
    foreach ($this->hotel as $key => $value) {
        echo "<tr>" .
        "<td>" . $value['id'] . "</td>" .
        "<td>" . $value['name'] . "</td>" .
        "<td>" . $value['location_id'] . "</td>" .
        "<td> <a href='../admin/edithotel/id/" . $value['id'] . "' class='btn btn-warning'> Edit </a> </td>".
        "<td> <a href='../admin/deletehotel/id/" . $value['id'] . "' class='btn btn-danger'> Delete </a> </td>".
        "</tr>";
    }
    ?>
</table>     