<?php
 if($this->country !== null)
  {
  	//var_dump($this->user["id"] );exit;
  	?>

<div class="item">
	<img src="<?=  $this->country["image"];?>"  style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h3><?=  $this->country["name"]; ?></h3>
          <p><?= $this->country["description"];?></p>
        </div>
</div>	
</tr>

<?php
  }
?>

<?php
echo "<table>";
//var_dump( $this->country);exit();
echo "<td> <a class='btn btn-info' href='/city/add'> ADD </a> </td>" ;
foreach($this->cites as $key => $value)
{

echo "<tr>".
"<td>" . $value['id']
. "</td>" .
"<td>" . $value['name'] . "</td>" .
"<td>" . $value['description'] . "</td>" .
//"<td>" . $value['image'] . "</td>" .
"<td> <img  src='".$value['image']."' height='42' width='42'>  </td>" .

//"<td> <a class='btn btn-info' href='/city/details/id/".$value['id']."/country_id/".$value['country_id']."'> Details </a> </td>" .
"<td> <a class='btn btn-info' href='/city/details/id/".$value['id']."/country_id/".$value['country_id']."'> Details </a> </td>" .

"<td> <a class='btn btn-warning' href='/city/delete/id/".$value['id']."/country_id/".$value['country_id']."'> Delete </a> </td>" .
"<td> <a class='btn btn-primary' href='/city/edit/id/".$value['id']."'> Edit </a> </td>" .
"</tr>";


}
echo "</table>";
?>

