<head>
    <script language="javascript" type="text/javascript">
        //anynomous function to inital the page 
        (function (a) {
            // execute the initalization of the page style 
            a.fn.codexworld_rating_widget = function (p) {
                var b = p.starLength ? p.starLength : "5";
                var c = p.callbackFunctionName ? p.callbackFunctionName : "";
                var e = p.initialValue ? p.initialValue : "0";
                var r = p.inputAttr ? p.inputAttr : "";
                var g = a(this);
                init();
                g.next("ul").children("li").hover(function () {
                    $(this).parent().children("li").css('background-position', '0px 0px');

                    var a = $(this).parent().children("li").index($(this));
                    $(this).parent().children("li").slice(0, a + 1).css('background-position', '0px -28px')
                }, function () {
                });

                g.next("ul").children("li").click(function () {
                    var a = $(this).parent().children("li").index($(this));
                    var attrVal = (r != '') ? g.attr(r) : '';
                    f = a + 1;
                    g.val(f);
                    if (c != "") {
                        eval(c + "(" + g.val() + ", " + attrVal + ")")
                    }
                });

                g.next("ul").hover(function () {
                }, function () {
                    if (f == "") {
                        $(this).children("li").slice(0, f).css('background-position', '0px 0px')
                    } else {
                        $(this).children("li").css('background-position', '0px 0px');
                        $(this).children("li").slice(0, f).css('background-position', '0px -28px')
                    }
                });
                function init() {
                    $('<div style="clear:both;"></div>').insertAfter(g);
                    g.css("float", "left");
                    var a = $("<ul>");
                    a.addClass("codexworld_rating_widget");
                    for (var i = 1; i <= b; i++) {
                        a.append('<li style="background-image:url(/images/widget_star.gif)"><span>' + i + '</span></li>')
                    }
                    a.insertAfter(g);
                    if (e != "") {
                        f = e;
                        g.val(e);
                        g.next("ul").children("li").slice(0, f).css('background-position', '0px -28px')
                    }
                }
            }
        })(jQuery);



        $(function () {
            $("#rating_star").codexworld_rating_widget({
                starLength: '5',
                initialValue: prevrate(),
                callbackFunctionName: 'processRating',
                imageDirectory: '/images/',
                inputAttr: 'postID'
            });
        });

        function prevrate() {
            var x = $.ajax({
                url: "/country/getrate",
                type:'POST',
                data: 'id=' + 1 + '&user_id='+ 2 ,
                async: false,
            }).responseText;
            return x;
        }

        function processRating(val, attrVal) {
            $.ajax({
                type: 'POST',
                url: '/country/addrate',
                data: 'id=' + attrVal + '&user_id='+ 2 +  '&ratingPoints=' + val,
                dataType: 'json'
            });
        }
    </script>
    <style type="text/css">
        .overall-rating{font-size: 14px;margin-top: 5px;color: #8e8d8d;}
        .codexworld_rating_widget{
            padding: 0px;
            margin: 0px;
            float: left;
        }
        .codexworld_rating_widget li{
            line-height: 0px;
            width: 28px;
            height: 28px;
            padding: 0px;
            margin: 0px;
            margin-left: 2px;
            list-style: none;
            float: left;
            cursor: pointer;
        }
        .codexworld_rating_widget li span{
            display: none;
        }
    </style>
</head>


<?php
 if($this->country !== null)
  {
  	//var_dump($this->user["id"] );exit;
  	?>
<div class="item">
	<img src="<?=  $this->country["image"];?>"  style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h3><?=  $this->country["name"]; ?></h3>
          <p><?= $this->country["description"];?></p>
        </div>
</div>	


<?php
  }
?>
<br/>
    <div>
    <input name="rating" value="0" id="rating_star" type="hidden" postID="1" />
    </div>
<br/>
<?php
echo "<table>";
//var_dump( $this->country);exit();
echo "<td> <a class='btn btn-info' href='/city/add'> ADD </a> </td>" ;
foreach($this->cites as $key => $value)
{

echo "<tr>".
"<td>" . $value['id']
. "</td>" .
"<td>" . $value['name'] . "</td>" .
"<td>" . $value['description'] . "</td>" .
//"<td>" . $value['image'] . "</td>" .
"<td> <img  src='".$value['image']."' height='42' width='42'>  </td>" .

//"<td> <a class='btn btn-info' href='/city/details/id/".$value['id']."/country_id/".$value['country_id']."'> Details </a> </td>" .
"<td> <a class='btn btn-info' href='/city/details/id/".$value['id']."/country_id/".$value['country_id']."'> Details </a> </td>" .

"<td> <a class='btn btn-warning' href='/city/delete/id/".$value['id']."/country_id/".$value['country_id']."'> Delete </a> </td>" .
"<td> <a class='btn btn-primary' href='/city/edit/id/".$value['id']."'> Edit </a> </td>" .
"</tr>";


}
echo "</table>";
?>

<h2>available location in country <?php echo "( ".$this->countItems." )"; ?></h2> 
<table class="table table-hover">
 <?php foreach ($this->cites as $tree): ?>
    <tr>
    <td>
        
        <a href="/city/details/id/<?= $tree['id'] ?>/country_id/<?= $this->country['id'] ?>"> READ MORE</a><br>
    </td>
    <td>
    <h1><?= $tree['name'] ?></h1><br>
    <h1> <?= $tree['description'] ?></h1><br>
   
   <img src='<?= $tree['image'] ?>'style='width: 200px;height: 200px'><br>
   </td>
    </tr>
 <?php endforeach; ?> 
</table> <br/> 
<a href="<?php echo $this->url(array('controller'=>'country','action'=>'details','p'=>$this->previousPage)) ?>">
    previous </a> 
        <?php echo "".$this->currentPage."/".$this->countPages; ?> 
<a href="<?php echo $this->url(array('controller'=>'country','action'=>'details','p'=>$this->nextPage)) ?>"> next </a> <br/>