<style>
 

 
  .carousel-inner img {
     
      width: 100%; /* Set width to 100% */
      margin: auto;
  }
 
  


 
  </style>
 
      
      
      
      <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown Example
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
         <?php foreach($this->country as $key=>$value ): ?>
      <li><a href="country/details/id/<?= $value['id']?>"><?= $value['name']?></a></li>
        <?php endforeach ;?>
     
    </ul>
  </div>
      
      
      






<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
      <li data-target="#myCarousel" data-slide-to="5"></li>
    </ol>

<!--    
       foreach($this->countryarr as $key=>$value)
        
   {
//  echo  "<div class='carousel-inner' role='listbox'>";
//     echo "<div class='item active'>";
//    // var_dump($value[0]['image']); exit;
//       echo "<img src='".$value[0]['image']."'" ." width='1200' height='700'>";
//        echo "<div class='carousel-caption'>";
//         echo  "<h3>".$value[0]['name']."</h3>";
//       echo "</div>";      
//     echo "</div>";
// echo "</div>";
//    }
    -->
    
    
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="<?=  $this->countryarr[0][0]['image'];?>"  style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h1><?=  $this->countryarr[0][0]['name'];?></h1>
          <h3>  <a href="/country/details/id/<?=  $this->countryarr[0][0]['id'];?>">ReadMore</a></h3>
        </div>      
       
      </div>
        
        <div class="item">
            <img src="<?= $this->countryarr[1][0]['image'];?>" alt="Chicago" style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h3><?=  $this->countryarr[1][0]['name'];?></h3>
           <h3>  <a href="/country/details/id/<?=  $this->countryarr[1][0]['id'];?>">ReadMore</a></h3>
        </div>      
      </div>
    
      <div class="item">
        <img src="<?= $this->countryarr[2][0]['image'];?>" alt="Los Angeles"  style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h3><?=  $this->countryarr[2][0]['name'];?></h3>
          <h3>  <a href="/country/details/id/<?=  $this->countryarr[2][0]['id'];?>">ReadMore</a></h3>
        </div>      
      </div>
        
        <div class="item">
        <img src="<?= $this->countryarr[3][0]['image'];?>" alt="Los Angeles"  style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h3><?=  $this->countryarr[3][0]['name'];?></h3>
          <h3>  <a href="/country/details/id/<?=  $this->countryarr[3][0]['id'];?>">ReadMore</a></h3>
        </div>      
      </div>
        <div class="item">
        <img src="<?= $this->countryarr[4][0]['image'];?>" alt="Los Angeles"  style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h3><?=  $this->countryarr[4][0]['name'];?></h3>
           <h3>  <a href="/country/details/id/<?=  $this->countryarr[4][0]['id'];?>">ReadMore</a></h3>
        </div>      
      </div>
        <div class="item">
        <img src="<?= $this->countryarr[5][0]['image'];?>" alt="Los Angeles"  style="width: 1800px ; height: 500px">
        <div class="carousel-caption">
          <h3><?=  $this->countryarr[5][0]['name'];?></h3>
           <h3>  <a href="/country/details/id/<?=  $this->countryarr[5][0]['id'];?>">ReadMore</a></h3>
        </div>      
      </div>
</div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>






<div id="hello" class="banner-bottom">
	<div class="container">
		<div class="btm-header">
			<h3 class="tittle">HELLO!</h3>
		
		</div>
		
		
	</div>
</div>





<div class="collections">
	<div class="container">
		<h3 class="tittle-two">CITIES</h3>
		<div class="collection-grids cs-style-1">
			<div class="col-md-4 collection-grid grid">
				<figure>
						<img src="<?=  $this->cityarr[0][0]['image'];?>"alt="">
						<figcaption>
							<h3><?=  $this->cityarr[0][0]['name'];?></h3>
							<span><?=  $this->cityarr[0][0]['description'];?></span>
							<a class="example-image-link" href="/city/details/id/<?=  $this->cityarr[0][0]['id'];?>/country_id/<?=  $this->cityarr[0][0]['country_id'];?>" data-lightbox="example-1" data-title="Luxus">VIEW</a>
						</figcaption>
				</figure>
			</div>	
			<div class="col-md-8 collection-grid grid">
				<figure>
						<img src="<?= $this->cityarr[1][0]['image'];?>" alt="">
						<figcaption>
							<h3><?=  $this->cityarr[1][0]['name'];?></h3>
							<span><?=  $this->cityarr[1][0]['description'];?></span>
                                                        <a class="example-image-link" href="/city/details/id/<?=  $this->cityarr[1][0]['id'];?>/country_id/<?=  $this->cityarr[1][0]['country_id'];?>" data-lightbox="example-1" data-title="Luxus">VIEW</a>
						</figcaption>
				</figure>
			</div>
			<div class="col-md-4 collection-grid grid">
				<figure>
						<img src="<?=  $this->cityarr[2][0]['image'];?>" alt="">
						<figcaption>
							<h3><?=  $this->cityarr[2][0]['name'];?></h3>
							<span><?=  $this->cityarr[2][0]['description'];?></span>
                                                        <a class="example-image-link" href="/city/details/id/<?=  $this->cityarr[2][0]['id'];?>/country_id/<?=  $this->cityarr[2][0]['country_id'];?>" data-lightbox="example-1" data-title="Luxus">VIEW</a>
						</figcaption>
				</figure>
			</div>	
			<div class="col-md-4 collection-grid grid">
				<figure>
						<img src="<?=  $this->cityarr[3][0]['image'];?>" alt="">
						<figcaption>
							<h3><?=  $this->cityarr[3][0]['name'];?></h3>
							<span><?=  $this->cityarr[3][0]['description'];?></span>
                                                        <a class="example-image-link" href="/city/details/id/<?=  $this->cityarr[3][0]['id'];?>/country_id/<?=  $this->cityarr[3][0]['country_id'];?>" data-lightbox="example-1" data-title="Luxus">VIEW</a>
						</figcaption>
				</figure>
			</div>	
			<div class="col-md-4 collection-grid grid">
				<figure>
						<img src="<?=  $this->cityarr[4][0]['image'];?>" alt="">
						<figcaption>
							<h3><?=  $this->cityarr[4][0]['name'];?></h3>
							<span><?=  $this->cityarr[4][0]['description'];?></span>
          <a class="example-image-link" href="/city/details/id/<?=  $this->cityarr[4][0]['id'];?>/country_id/<?=  $this->cityarr[4][0]['country_id'];?>" data-lightbox="example-1" data-title="Luxus">VIEW</a>

						</figcaption>
				</figure>
			</div>
			<div class="col-md-8 collection-grid grid">
				<figure>
						<img src="<?=  $this->cityarr[5][0]['image'];?>" alt="">
						<figcaption>
							<h3><?=  $this->cityarr[5][0]['name'];?></h3>
							<span><?=  $this->cityarr[5][0]['description'];?></span>
          <a class="example-image-link" href="/city/details/id/<?=  $this->cityarr[5][0]['id'];?>/country_id/<?=  $this->cityarr[5][0]['country_id'];?>" data-lightbox="example-1" data-title="Luxus">VIEW</a>
						</figcaption>
				</figure>
			</div>	
			<div class="clearfix"></div>
		</div>
		 <script src="js/lightbox.js"></script>
	</div>








 <div >
      <ul class=" nav navbar-nav navbar-right">
          <li class='dropdown'>
              <a href="#" class="dropdown-toggle" data-toggle="drop">Destination</a></li>
          <ul class='dropdown-menu'>
              <?php foreach($this->country as $key=>$value ): ?>
              <li><a href="country/details/id/<?= $value['id']?>"><?= $value['name']?></a>
                  <?php endforeach ;?>
              
          </ul>          
      </li>
      </ul>

      
  </div>




























<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip(); 
  
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){
   
      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
    });
  });
})


</script>
